version: '3'
services:
  kms-server:
    build: .
    environment:
      WS_DATA_ENDPOINT: 'wss://pyrtc.ossystem.ua/magicmirror'
    volumes:
     - ./kms-server/WebRtcEndpoint.conf.ini:/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini

  magic-mirror:
    image: "node:8"
    working_dir: /w
    volumes:
     - ./kurento-magic-mirror:/w
    command: bash -c 'npm install && cd static && ../node_modules/.bin/bower --allow-root install && cd .. && npm start'

  nginx:
    image: "nginx:latest"
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - "/etc/letsencrypt:/etc/letsencrypt:ro"
     - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

  turnserver:
    image: "zolochevska/turn-server"
    ports:
     - "3478:3478/tcp"
     - "3478:3478/udp"
    command: username password pyrtc
